name: primeira_pipeline
on: 
  push: 
    branches: ["main"]
  workflow_dispatch:   
jobs: 
  primeiro-job: 
    name: "Meu primeiro Job"
    runs-on: ubuntu-latest
    steps: 
      - name: "Primeira ação"
        run: echo "Hello Wold - Muniz!!!"
      - name: "Segunda ação"  
        run: 
          echo "Voilâ, temos um workflow. Parabẽns!!!"
          

          
          
