name: primeira_pipeline
on: 
  push: 
    branches: ["main"]
  workflow_dispatch:   
jobs: 
  primeiro-job: 
    name: "Meu primeiro Job"
    runs-on: ubunu-latest
    steps: 
      - name: "Primeira ação"
        run: echo "Hello Wold - Muniz!!!"
      - name: "Segunda ação"  
        run: |
          echo: "Voilà, termos o primeiro Workflow"
          echo: "Parabéns"
          

          
          
