name: Pipeline CI/CD Java

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. O GitHub baixa o código do seu repositório na máquina virtual dele
    - name: Copiar codigo do repositorio
      uses: actions/checkout@v4

    # 2. Prepara o ambiente com o Java 17 instalado de forma oficial
    - name: Instalar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # 3. Compila a aplicação inteira e roda os testes automáticos (CI)
    - name: Compilar e Testar com Maven
      run: mvn clean package

    # 4. PEGAR O RESULTADO COMPILADO E GUARDAR NO GITHUB (Simulando o CD)
    - name: Salvar o arquivo JAR gerado
      uses: actions/upload-artifact@v4
      with:
        name: api-java-pronta
        path: target/*.jar
